# Configuración del pid
#   kp, ki, y kd son las ganancias del control
#   isats son las saturaciones para el integral
# No hay saturación para las señales de control, si se quiere saturar,
# que se haga aparte
fvel_pid:
    kp: 3.0
    ki: 0.1
    kd: 0.05
    isats: [-1.0, 1.0]

yr_pid:
    kp: 0.7
    ki: 0.0
    kd: 0.05
    isats: [-0.5, 0.5]

y_pid:
    kp: 0.5
    ki: 0.0
    kd: 0.05
    isats: [-0.5, 0.5]

velocity_topic:
    odometry/filtered

twist_ref_topic:
    control/twist_ref
course_ref_topic:
    control/course_ref

command_topic:
    miniASV/command

command_motor_topic:
    cmd_pwm

command_wrench_topic:
    cmd_wrench